Repository HotCakeX/Harden-Windows-Security, pull requests merged in 2023-12, with the labels that each got.

#162 Documentations update
  README.md
  Wiki posts/Azure/Clean Source principle, Azure and Privileged Access Workstations.md
  Wiki posts/Azure/How to Securely Connect to Azure VMs and Use RDP.md
  Wiki posts/Home Index.md
  Wiki posts/Miscellaneous/About TLS, DNS, Encryption and OPSEC concepts.md
  Wiki posts/Miscellaneous/Answers to the Basic Frequently Asked Questions.md
  Wiki posts/Miscellaneous/Comparison of security benchmarks.md
  Wiki posts/Miscellaneous/Device Guard and Virtualization Based Security in Windows.md
  Wiki posts/Miscellaneous/Event Viewer.md
  Wiki posts/Miscellaneous/How to Detect Changes in User and Local Machine Certificate Stores in Real Time Using PowerShell.md
  Wiki posts/PowerShell/Basic PowerShell tricks and notes Part 2.md
  Wiki posts/PowerShell/Basic PowerShell tricks and notes Part 3.md
  Wiki posts/PowerShell/Basic PowerShell tricks and notes.md
  Wiki posts/WDACConfig Module Main/Confirm-WDACConfig.md
  Wiki posts/WDACConfig Module Main/Deploy-SignedWDACConfig.md
  Wiki posts/WDACConfig Module Main/Edit-SignedWDACConfig.md
  Wiki posts/WDACConfig Module Main/Edit-WDACConfig.md
  Wiki posts/WDACConfig Module Main/Get-CommonWDACConfig.md
  Wiki posts/WDACConfig Module Main/Invoke-WDACSimulation.md
  Wiki posts/WDACConfig Module Main/New-DenyWDACConfig.md
  Wiki posts/WDACConfig Module Main/New-KernelModeWDACConfig.md
  Wiki posts/WDACConfig Module Main/New-SupplementalWDACConfig.md
  Wiki posts/WDACConfig Module Main/New-WDACConfig.md
  Wiki posts/WDACConfig Module Main/Remove-WDACConfig.md
  Wiki posts/WDACConfig Module Main/Set-CommonWDACConfig.md
  Wiki posts/WDACConfig Module Main/WDACConfig.md
  Wiki posts/Windows Defender Application Control (WDAC)/How to Create and Deploy a Signed WDAC Policy.md
  Wiki posts/Windows Defender Application Control (WDAC)/WDAC Notes.md
  Wiki posts/Windows Defender Application Control (WDAC)/WDAC for Fully managed device - Variant 1.md
  Wiki posts/Windows Defender Application Control (WDAC)/WDAC for Fully managed device - Variant 2.md
  Wiki posts/Windows Defender Application Control (WDAC)/WDAC for Fully managed device - Variant 4.md
  Wiki posts/Windows Defender Application Control (WDAC)/WDAC for Lightly Managed Devices.md
  Wiki posts/Windows Defender Application Control (WDAC)/WDAC policy for BYOVD Kernel mode only protection.md
Labels: Documentation 📃

#164 Stricter Types
  WDACConfig/WDACConfig Module Files/Shared/Write-ColorfulText.psm1
Labels: Enhancement 💯

#167 Fixed an error encountered when using Windows PowerShell
  Harden-Windows-Security Module/Main files/Resources/Harden-Windows-Security.ps1
  Harden-Windows-Security.ps1
Labels: Bug 🐛

#168 Fixed broken link in Rationale
  Rationale.md
Labels: Documentation 📃

#171 WDACConfig documents update
  Wiki posts/WDACConfig Module Main/Edit-SignedWDACConfig.md
  Wiki posts/WDACConfig Module Main/Edit-WDACConfig.md
  Wiki posts/WDACConfig Module Main/New-KernelModeWDACConfig.md
  Wiki posts/Windows Defender Application Control (WDAC)/WDAC for Fully managed device - Variant 2.md
  Wiki posts/Windows Defender Application Control (WDAC)/WDAC for Fully managed device - Variant 3.md
  Wiki posts/Windows Defender Application Control (WDAC)/WDAC for Fully managed device - Variant 4.md
  Wiki posts/Windows Defender Application Control (WDAC)/WDAC for Lightly Managed Devices.md
Labels: Documentation 📃

#173 Create Hashes.csv
  WDACConfig/Utilities/Hashes.csv
Labels: Enhancement 💯

#174 Added documentation for Assert-WDACConfigIntegrity
  Wiki posts/WDACConfig Module Main/Assert-WDACConfigIntegrity.md
Labels: Documentation 📃

#165 WDACConfig update v0.2.8
  WDACConfig/Utilities/Certificate/HotCakeX Root CA.cer
  WDACConfig/Utilities/Hashes.csv
  WDACConfig/Utilities/Invoke-WDACConfig.ps1
  WDACConfig/WDACConfig Module Files/Core/Assert-WDACConfigIntegrity.psm1
  WDACConfig/WDACConfig Module Files/Core/Confirm-WDACConfig.psm1
  WDACConfig/WDACConfig Module Files/Core/Deploy-SignedWDACConfig.psm1
  WDACConfig/WDACConfig Module Files/Core/Edit-SignedWDACConfig.psm1
  WDACConfig/WDACConfig Module Files/Core/Edit-WDACConfig.psm1
  WDACConfig/WDACConfig Module Files/Core/Get-CommonWDACConfig.psm1
  WDACConfig/WDACConfig Module Files/Core/Invoke-WDACSimulation.psm1
  WDACConfig/WDACConfig Module Files/Core/New-DenyWDACConfig.psm1
  WDACConfig/WDACConfig Module Files/Core/New-KernelModeWDACConfig.psm1
  WDACConfig/WDACConfig Module Files/Core/New-SupplementalWDACConfig.psm1
  WDACConfig/WDACConfig Module Files/Core/New-WDACConfig.psm1
  WDACConfig/WDACConfig Module Files/Core/Remove-CommonWDACConfig.psm1
  WDACConfig/WDACConfig Module Files/Core/Remove-WDACConfig.psm1
  WDACConfig/WDACConfig Module Files/Core/Set-CommonWDACConfig.psm1
  WDACConfig/WDACConfig Module Files/CoreExt/PSDefaultParameterValues.ps1
  WDACConfig/WDACConfig Module Files/Preloader.ps1
  WDACConfig/WDACConfig Module Files/Resources/ArgumentCompleters.ps1
  WDACConfig/WDACConfig Module Files/Resources/Resources2.ps1
  WDACConfig/WDACConfig Module Files/Shared/Confirm-CertCN.psm1
  WDACConfig/WDACConfig Module Files/Shared/Get-AuditEventLogsProcessing.psm1
  WDACConfig/WDACConfig Module Files/Shared/Get-BlockRulesMeta.psm1
  WDACConfig/WDACConfig Module Files/Shared/Get-FileRules.psm1
  WDACConfig/WDACConfig Module Files/Shared/Get-GlobalRootDrives.psm1
  WDACConfig/WDACConfig Module Files/Shared/Get-RuleRefs.psm1
  WDACConfig/WDACConfig Module Files/Shared/Get-SignTool.psm1
  WDACConfig/WDACConfig Module Files/Shared/Move-UserModeToKernelMode.psm1
  WDACConfig/WDACConfig Module Files/Shared/New-EmptyPolicy.psm1
  WDACConfig/WDACConfig Module Files/Shared/New-SnapBackGuarantee.psm1
  WDACConfig/WDACConfig Module Files/Shared/Set-LogSize.psm1
  WDACConfig/WDACConfig Module Files/Shared/Test-FilePath.psm1
  WDACConfig/WDACConfig Module Files/Shared/Update-self.psm1
  WDACConfig/WDACConfig Module Files/Shared/Write-ColorfulText.psm1
  WDACConfig/WDACConfig Module Files/WDACConfig.psd1
  WDACConfig/WDACConfig Module Files/WDACConfig.psm1
  WDACConfig/WDACConfig.code-workspace
  WDACConfig/version.txt
  Wiki posts/WDACConfig Module Main/Assert-WDACConfigIntegrity.md
Labels: Enhancement 💯
